ifdef::env-github[{set:link-ext:adoc}]
ifndef::env-github[{set:link-ext:html}]

== DCS-FlighPanel-Profiles

Collection of DCS WORLD Profiles for DCSFlightpanels

== Instructions

Put these files in a Folder and open it in DCSFlightpanels.

Before use, open the files with a text editor and change PanelInstanceID= to your IDs

1. start dcsfp.exe
2. open a profile and close the announcement (The XXX Panel with ID xyzxyzxyz cannot found)
3. execute the ID button to copy the id no. to clipboard
4. open the profile (*.bindings file) in Notepad, Notepad++,...
5. paste the contents of the clipboard to here :
PanelInstanceID=\\?\xyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxy
6. that will change the ID of the USB address for the panel to that of your panel

== Support

* If you have some Profiles to share please contact me (WarLord) on our Discord Server
* Here you find our https://discord.gg/5svGwKX[DCSFlightpanels Discord Server]
* Here you find the https://github.com/DCSSkunkworks/DCSFlightpanels[DCSFlightPanels]
* Here you find the https://github.com/DCSSkunkworks/dcs-bios[DCS-BIOS]
* Here you find the https://github.com/ciribob/DCS-SimpleRadioStandalone[DCS-SimpleRadioStandalone]
* If you want to support us: https://www.paypal.me/jerkerdahlblom[Here you can Donate.] 
